#!/usr/bin/env bash
#
# Teach Xcode's Archive about the app's dart-defines.
#
# ── The problem this solves ──────────────────────────────────────────────────
#
# The API base URL is a COMPILE-TIME constant (`String.fromEnvironment`), which
# is deliberate — a URL read at runtime is a URL an attacker can move. It comes
# from `--dart-define`, and `flutter build` passes those through.
#
# Product → Archive in the Xcode UI does not. It runs the Flutter build phase
# with whatever `DART_DEFINES` is already in the environment, so an archive made
# that way carries none of ours and the app falls back to its dev default:
# http://10.0.2.2:3000, the ANDROID EMULATOR's route to its host. On a real
# iPhone that address goes nowhere. The build installs, looks correct, and every
# screen sits on its retry state — which is exactly the "uploaded to TestFlight
# and it's empty" failure this script exists to prevent.
#
# ── How it works ─────────────────────────────────────────────────────────────
#
# `xcode_backend.dart` reads the `DART_DEFINES` environment variable: a
# comma-separated list of base64-encoded `KEY=VALUE` pairs. Xcode turns build
# settings into environment variables, so writing that variable into an xcconfig
# is enough. `Flutter/Generated.xcconfig` already sets it (Flutter's own
# version defines live there), it is rewritten by every build and it is
# gitignored — so this appends to it with `$(inherited)` rather than replacing
# it, which would drop FLUTTER_BUILD_NAME and friends on the floor.
#
# Usage:  tool/sync-dart-defines.sh [dev|staging|prod]     (default: prod)
#
# Re-run it whenever dart_defines/*.json changes, or to switch which environment
# an Xcode archive targets. The generated file names the environment it holds,
# so `git status` and the xcconfig itself both say what an archive would build.
set -euo pipefail

ENV_NAME="${1:-prod}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$HERE/dart_defines/$ENV_NAME.json"
OUT="$HERE/ios/Flutter/DartDefines.xcconfig"

[ -f "$SRC" ] || { echo "No such environment: $SRC" >&2; exit 1; }

# Base64 each KEY=VALUE, exactly as the flutter tool does.
CSV="$(python3 - "$SRC" <<'PY'
import base64, json, sys
data = json.load(open(sys.argv[1]))
print(",".join(
    base64.b64encode(f"{k}={v}".encode()).decode()
    for k, v in data.items()
))
PY
)"

cat > "$OUT" <<EOF
// GENERATED by tool/sync-dart-defines.sh — DO NOT EDIT.
//
// Environment: $ENV_NAME
$(python3 -c "
import json,sys
for k,v in json.load(open('$SRC')).items(): print(f'//   {k} = {v}')
")
//
// \$(inherited) keeps Flutter's own defines (build name, build number, engine
// revision) that Generated.xcconfig sets. Replacing rather than appending here
// silently drops them.
DART_DEFINES=\$(inherited),$CSV
EOF

echo "wrote ios/Flutter/DartDefines.xcconfig for '$ENV_NAME':"
python3 -c "
import json
for k,v in json.load(open('$SRC')).items(): print(f'    {k} = {v}')
"
