-- A colleague of an existing member can apply to join their company.
--
-- Until now a second person at a company that was already registered had one
-- route in: their administrator typed their address into the team page. If
-- nobody did, the CR check refused them ("A company is already registered with
-- that commercial registration number") and the journey ended there.
--
-- This adds the two things that route needed and did not have:
--
--   Company.emailDomains  the domains a company is recognised at, so that
--                         "does this person actually work there?" has an answer
--                         before a human is asked to look.
--   CompanyJoinRequest    the application itself, which is NOT a membership. A
--                         membership row is authority (getB2BContext reads it to
--                         decide whose prices a user sees); this row is a
--                         request, and grants nothing until an administrator of
--                         that company promotes it.
--
-- GENERATED BY `prisma migrate diff`, not hand-written, then commented. The
-- hand-written alternative is what produced two migrations for one schema
-- change on this repo's last merge — one of them incomplete, and the pair
-- unrunnable in sequence. The backfill at the end is the only statement here
-- that diff did not write.
--
-- ADDITIVE. No column is dropped and no constraint narrowed.

-- CreateEnum
CREATE TYPE "CompanyJoinRequestStatus" AS ENUM ('PENDING_EMAIL_VERIFICATION', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'REJECTED');

-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "emailDomains" TEXT[];

-- CreateTable
CREATE TABLE "CompanyJoinRequest" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "CompanyJoinRequestStatus" NOT NULL DEFAULT 'PENDING_EMAIL_VERIFICATION',
    "requestedRole" "UserRole" NOT NULL DEFAULT 'COMPANY_BUYER',
    "department" TEXT,
    "emailDomain" TEXT NOT NULL,
    "emailVerifiedAt" TIMESTAMP(3),
    "decidedById" TEXT,
    "decidedAt" TIMESTAMP(3),
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CompanyJoinRequest_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CompanyJoinRequest_userId_key" ON "CompanyJoinRequest"("userId");

-- CreateIndex
CREATE INDEX "CompanyJoinRequest_companyId_status_createdAt_idx" ON "CompanyJoinRequest"("companyId", "status", "createdAt");

-- AddForeignKey
ALTER TABLE "CompanyJoinRequest" ADD CONSTRAINT "CompanyJoinRequest_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CompanyJoinRequest" ADD CONSTRAINT "CompanyJoinRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ─── Backfill: recognise each company at its founding admin's own domain ───
--
-- Without this every existing company starts with an empty list and the feature
-- is dark for all of them until somebody edits a row by hand.
--
-- Two conditions, both load-bearing:
--
--   1. COMPANY_ADMIN members only. A buyer invited from a personal address must
--      not be able to teach the company a domain.
--   2. NOT a public mailbox provider. A company whose administrator registered
--      with a gmail.com address must never come to claim gmail.com — that would
--      let any Gmail user on earth pass its "do you work here?" gate, which is
--      precisely the hole this feature exists to close. Such companies keep an
--      empty list and stay invite-only, which is the right answer and not a gap.
--
-- The provider list is duplicated from isPublicMailboxDomain() in
-- packages/utils. That is deliberate: SQL running once at migration time cannot
-- import TypeScript, and leaving the backfill out is worse than two copies of a
-- list that changes about once a decade.
UPDATE "Company" c
SET "emailDomains" = ARRAY[sub.domain]
FROM (
  SELECT DISTINCT ON (m."companyId")
         m."companyId",
         lower(split_part(u."email", '@', 2)) AS domain
  FROM "CompanyMember" m
  JOIN "User" u ON u."id" = m."userId"
  WHERE m."role" = 'COMPANY_ADMIN'
    AND m."isActive" = true
    AND position('@' in u."email") > 0
  ORDER BY m."companyId", m."joinedAt" ASC
) sub
WHERE c."id" = sub."companyId"
  AND sub.domain <> ''
  AND sub.domain NOT IN (
    'gmail.com', 'googlemail.com', 'yahoo.com', 'yahoo.co.uk', 'ymail.com',
    'hotmail.com', 'hotmail.co.uk', 'outlook.com', 'live.com', 'msn.com',
    'icloud.com', 'me.com', 'mac.com', 'aol.com', 'proton.me', 'protonmail.com',
    'gmx.com', 'gmx.net', 'mail.com', 'zoho.com', 'yandex.com', 'yandex.ru',
    'qq.com', '163.com', '126.com', 'naver.com', 'hushmail.com',
    'mailinator.com', 'yopmail.com', 'guerrillamail.com', '10minutemail.com',
    'tempmail.com', 'temp-mail.org', 'trashmail.com', 'sharklasers.com',
    'dispostable.com', 'getnada.com', 'maildrop.cc', 'fakeinbox.com'
  );
